---
title: "p8105_hw6_ss6692"
author: "Sanika Sule"
date: "`r Sys.Date()"
output: github_document
---
### Problem 2

```{r loading_libraries}
library(tidyverse)
library(dplyr)
library(p8105.datasets)
library(modelr)
library(mgcv)
```

Downloading weather data.

```{r loading weather_df}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2022-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

```{r boot_strapping}
boot_sample = function(df) {
  sample_df = df |> sample_frac(size = 1, replace = TRUE)
  model = lm(tmax ~ tmin + prcp, data = sample_df)

  # Getting r_squared values
  r_squared = broom::glance(model)[["r.squared"]]

  # Getting beta coefficients
  coef_df = broom::tidy(model)
  beta_tmin = coef_df |> filter(term == "tmin") |> pull(estimate)
  beta_prcp = coef_df |> filter(term == "prcp") |> pull(estimate)
  
# Because `βprcp` is a negative value. We expect `NaN` values for `log_beta`.
  
  # Calculating log of the product of beta_tmin and beta_prcp
  log_beta_product = log((beta_tmin) * (beta_prcp))

  # Creating a dataframe with both r_squared and log_beta_product
  return(data.frame(r_squared = r_squared, log_beta_product = log_beta_product))
}

boot_straps = 
  tibble(strap_number = 1:500) |> 
  mutate(
    bootstrap_results = map(strap_number, ~ boot_sample(weather_df))
  ) |> 
  unnest(bootstrap_results)

```

Distribution of r^2 values

```{r}
boot_straps |> 
  ggplot(aes(x = r_squared)) + 
  geom_density()
```

Distribution of `log(βprcp*βtmin)` values

```{r}
boot_straps |> 
  ggplot(aes(x = log_beta_product)) + 
  geom_density()
```
There are `322 non-finite values`, which will not be included in the `log(βprcp*βtmin)` plot.

### Problem 3
Cleaning birthweight data
```{r}
birthweight =
  read_csv("data/birthweight.csv") |> 
  janitor::clean_names() |> 
  mutate(babysex = as.factor(babysex))
```

For my proposed model, I will investigate the relationship between the mother's age at menarche `menarche` and the baby's birth weight `bwt`. 

```{r}
menarche_bwt = 
  birthweight |> 
  lm(bwt ~ menarche, data = _)
```

```{r}
birthweight_resids = birthweight |> 
  modelr::add_predictions(menarche_bwt) |> 
  modelr::add_residuals(menarche_bwt) |> 
  ggplot(aes(x = pred, y = resid)) + 
  geom_point() + 
  labs(title = "Residuals vs. Fitted Values",
       x = "Fitted Values",
       y = "Residuals")

```

